### ISSUE TITLE
logo for lastwords

### ISSUE THREAD

**Issue by hafizahmmed** [lovoo/lastwords#2]
Hello,
Good Day, i make a logo icon for your project.I make a 3 logo for you.Which logo do you like? If you want to use this logo in your project, then comment below, I will give you the source file. And if you want a change, then tell me I will change.It's totally free for open source project.

![lastwords-01](https://user-images.githubusercontent.com/38810169/40833867-ede4dc00-65b0-11e8-9516-afb7a10cbee3.png)

**Comment by mario222k** [comment]
Hello @hafizahmmed,
we thank you for your kind offer. 

The provided lastwords app within this repository is just an example of how to use the library. Therefore the default android icon is good enough.
